# Generated by Django 2.1.5 on 2020-04-25 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200425_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='last_update',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='state',
            name='last_update',
            field=models.DateTimeField(),
        ),
    ]
